---
# handlers file for mysql
- name: mysql service status
  shell: ps aux | grep mysql | grep -v grep
  register: mysql_status
- name: mysql_process_running
  debug:
    msg: "{{ mysql_status.stdout_lines }}"

- name: Get Slave
  mysql_replication:
    mode: getslave
    login_user: root
    login_password: "{{ root_pass }}"
    login_unix_socket: "{{ mysqlsock }}"
  register: slave_status
  when: mysql_role == "slave"
- name: Slave_IO_Running
  debug: msg="Slave_IO_Running {{ slave_status.Slave_IO_Running }}"
  when: mysql_role == "slave"
- name: Slave_SQL_Running
  debug: msg="Slave_SQL_Running {{ slave_status.Slave_SQL_Running }}"
  when: mysql_role == "slave"
